services:
  postgres:
    image: postgis/postgis
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: haslo123
      POSTGRES_DB: pomniki
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: